spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springMicroservices
    username: postgres
    password: lenin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
