spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/springMicroservices
#  host.docker.internal
    username: postgres
    password: lenin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
