spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springMicroservices?currentSchema=public
    username: postgres
    password: lenin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: Asia/Kolkata
